/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdsBySubCategory`; params?: Router.UnknownInputParams; } | { pathname: `/Advertisement`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/FreshAd`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Map`; params?: Router.UnknownInputParams; } | { pathname: `/MyAds`; params?: Router.UnknownInputParams; } | { pathname: `/OtpVerification`; params?: Router.UnknownInputParams; } | { pathname: `/PopularAds`; params?: Router.UnknownInputParams; } | { pathname: `/Screenheader`; params?: Router.UnknownInputParams; } | { pathname: `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/SubCategory`; params?: Router.UnknownInputParams; } | { pathname: `/Themecontext`; params?: Router.UnknownInputParams; } | { pathname: `/UpdateAdvertisement`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AdsBySubCategory`; params?: Router.UnknownOutputParams; } | { pathname: `/Advertisement`; params?: Router.UnknownOutputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/Footer`; params?: Router.UnknownOutputParams; } | { pathname: `/FreshAd`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Map`; params?: Router.UnknownOutputParams; } | { pathname: `/MyAds`; params?: Router.UnknownOutputParams; } | { pathname: `/OtpVerification`; params?: Router.UnknownOutputParams; } | { pathname: `/PopularAds`; params?: Router.UnknownOutputParams; } | { pathname: `/Screenheader`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/SubCategory`; params?: Router.UnknownOutputParams; } | { pathname: `/Themecontext`; params?: Router.UnknownOutputParams; } | { pathname: `/UpdateAdvertisement`; params?: Router.UnknownOutputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AdsBySubCategory${`?${string}` | `#${string}` | ''}` | `/Advertisement${`?${string}` | `#${string}` | ''}` | `/EditProfile${`?${string}` | `#${string}` | ''}` | `/Footer${`?${string}` | `#${string}` | ''}` | `/FreshAd${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/Map${`?${string}` | `#${string}` | ''}` | `/MyAds${`?${string}` | `#${string}` | ''}` | `/OtpVerification${`?${string}` | `#${string}` | ''}` | `/PopularAds${`?${string}` | `#${string}` | ''}` | `/Screenheader${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `/SubCategory${`?${string}` | `#${string}` | ''}` | `/Themecontext${`?${string}` | `#${string}` | ''}` | `/UpdateAdvertisement${`?${string}` | `#${string}` | ''}` | `/UserProfile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdsBySubCategory`; params?: Router.UnknownInputParams; } | { pathname: `/Advertisement`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/FreshAd`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Map`; params?: Router.UnknownInputParams; } | { pathname: `/MyAds`; params?: Router.UnknownInputParams; } | { pathname: `/OtpVerification`; params?: Router.UnknownInputParams; } | { pathname: `/PopularAds`; params?: Router.UnknownInputParams; } | { pathname: `/Screenheader`; params?: Router.UnknownInputParams; } | { pathname: `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/SubCategory`; params?: Router.UnknownInputParams; } | { pathname: `/Themecontext`; params?: Router.UnknownInputParams; } | { pathname: `/UpdateAdvertisement`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
